 algoritimo
8
9 num vetor[0..3] de inteiro
10 votos, i, j, contl, cont2: inteiro
11 Inicio
12 // Seção de Comandos, procedimento,
13
14 repita
15 escreval("leia o no do candidato")
16 leia (num
[i])
171<-i + 1
18 votos <- votos + 1
19 limpatela
20 até votos = 4
21 escreval("fim da sessão")
22 para j de 0 ate 3 faca
23 se num[j] = 13 entao 24 cont) <- cont) +1
25 fimse
26 se num[j] = 22 entao
27 cont2 <- cont2 + 1
28 fimse
29 fimpara
30 escreval ("votos para 13:", 31 escreval ("votos para 22:", cont2)
cont1)
32 Fimalgoritmo
33
