 alg
var

 num vetor[0..3] de inteiro
votos, i, j, contl, cont2: inteiro
Inicio
 // Seção de Comandos, procedimento,

 repita
 escreval("leia o no do candidato")
leia (num
[i])
1<-i + 1
 votos <- votos + 1
 limpatela
 até votos = 4
 escreval("fim da sessão")
 para j de 0 ate 3 faca
 se num[j] = 13 entao 24 cont) <- cont) +1
 fimse
 se num[j] = 22 entao
 cont2 <- cont2 + 1
 fimse
 fimpara
 escreval ("votos para 13:", 31 escreval ("votos para 22:", cont2)
cont1)
 Fimalgoritmo

